backend:
  name: github
  repo: rafij90/MoneyMaths
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "News"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    preview_path: "articles/{{slug}}.html"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "Personal finance"
          - "Savings"
          - "Tax"
          - "Market"
          - "Startup"
          - "IPO"
      - { label: "Publish date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Body", name: "body", widget: "markdown" }