backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "content/articles"
    create: true
    slug: "{{slug}}"
    preview_path: "articles/{{slug}}.html"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Publish date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Body", name: "body", widget: "markdown" }